import {
  IN,
  US,
  GB,
  CA,
  AU,
  DE,
  FR,
  ES,
  IT,
  NL,
  SE,
  NO,
  DK,
  FI,
  CH,
  AT,
  BE,
  PT,
  IE,
  PL,
  CZ,
  HU,
  GR,
  JP,
  KR,
  CN,
  SG,
  HK,
  MY,
  TH,
  ID,
  PH,
  VN,
  BR,
  MX,
  AR,
  CL,
  CO,
  PE,
  ZA,
  EG,
  IL,
  AE,
  SA,
  TR,
  RU,
  UA,
  RO,
  BG,
  HR,
  SI,
  SK,
  LT,
  LV,
  EE,
  IS,
  LU,
  MT,
  CY,
  NZ,
} from "country-flag-icons/react/3x2";

export const countries = [
  { code: "IN", name: "India", flag: <IN title="India" className="w-6 h-4" /> },
  { code: "US", name: "United States", flag: <US title="United States" className="w-6 h-4" /> },
  { code: "GB", name: "United Kingdom", flag: <GB title="United Kingdom" className="w-6 h-4" /> },
  { code: "CA", name: "Canada", flag: <CA title="Canada" className="w-6 h-4" /> },
  { code: "AU", name: "Australia", flag: <AU title="Australia" className="w-6 h-4" /> },
  { code: "DE", name: "Germany", flag: <DE title="Germany" className="w-6 h-4" /> },
  { code: "FR", name: "France", flag: <FR title="France" className="w-6 h-4" /> },
  { code: "ES", name: "Spain", flag: <ES title="Spain" className="w-6 h-4" /> },
  { code: "IT", name: "Italy", flag: <IT title="Italy" className="w-6 h-4" /> },
  { code: "NL", name: "Netherlands", flag: <NL title="Netherlands" className="w-6 h-4" /> },
  { code: "SE", name: "Sweden", flag: <SE title="Sweden" className="w-6 h-4" /> },
  { code: "NO", name: "Norway", flag: <NO title="Norway" className="w-6 h-4" /> },
  { code: "DK", name: "Denmark", flag: <DK title="Denmark" className="w-6 h-4" /> },
  { code: "FI", name: "Finland", flag: <FI title="Finland" className="w-6 h-4" /> },
  { code: "CH", name: "Switzerland", flag: <CH title="Switzerland" className="w-6 h-4" /> },
  { code: "AT", name: "Austria", flag: <AT title="Austria" className="w-6 h-4" /> },
  { code: "BE", name: "Belgium", flag: <BE title="Belgium" className="w-6 h-4" /> },
  { code: "PT", name: "Portugal", flag: <PT title="Portugal" className="w-6 h-4" /> },
  { code: "IE", name: "Ireland", flag: <IE title="Ireland" className="w-6 h-4" /> },
  { code: "PL", name: "Poland", flag: <PL title="Poland" className="w-6 h-4" /> },
  { code: "CZ", name: "Czech Republic", flag: <CZ title="Czech Republic" className="w-6 h-4" /> },
  { code: "HU", name: "Hungary", flag: <HU title="Hungary" className="w-6 h-4" /> },
  { code: "GR", name: "Greece", flag: <GR title="Greece" className="w-6 h-4" /> },
  { code: "JP", name: "Japan", flag: <JP title="Japan" className="w-6 h-4" /> },
  { code: "KR", name: "South Korea", flag: <KR title="South Korea" className="w-6 h-4" /> },
  { code: "CN", name: "China", flag: <CN title="China" className="w-6 h-4" /> },
  { code: "SG", name: "Singapore", flag: <SG title="Singapore" className="w-6 h-4" /> },
  { code: "HK", name: "Hong Kong", flag: <HK title="Hong Kong" className="w-6 h-4" /> },
  { code: "MY", name: "Malaysia", flag: <MY title="Malaysia" className="w-6 h-4" /> },
  { code: "TH", name: "Thailand", flag: <TH title="Thailand" className="w-6 h-4" /> },
  { code: "ID", name: "Indonesia", flag: <ID title="Indonesia" className="w-6 h-4" /> },
  { code: "PH", name: "Philippines", flag: <PH title="Philippines" className="w-6 h-4" /> },
  { code: "VN", name: "Vietnam", flag: <VN title="Vietnam" className="w-6 h-4" /> },
  { code: "BR", name: "Brazil", flag: <BR title="Brazil" className="w-6 h-4" /> },
  { code: "MX", name: "Mexico", flag: <MX title="Mexico" className="w-6 h-4" /> },
  { code: "AR", name: "Argentina", flag: <AR title="Argentina" className="w-6 h-4" /> },
  { code: "CL", name: "Chile", flag: <CL title="Chile" className="w-6 h-4" /> },
  { code: "CO", name: "Colombia", flag: <CO title="Colombia" className="w-6 h-4" /> },
  { code: "PE", name: "Peru", flag: <PE title="Peru" className="w-6 h-4" /> },
  { code: "ZA", name: "South Africa", flag: <ZA title="South Africa" className="w-6 h-4" /> },
  { code: "EG", name: "Egypt", flag: <EG title="Egypt" className="w-6 h-4" /> },
  { code: "IL", name: "Israel", flag: <IL title="Israel" className="w-6 h-4" /> },
  { code: "AE", name: "United Arab Emirates", flag: <AE title="United Arab Emirates" className="w-6 h-4" /> },
  { code: "SA", name: "Saudi Arabia", flag: <SA title="Saudi Arabia" className="w-6 h-4" /> },
  { code: "TR", name: "Turkey", flag: <TR title="Turkey" className="w-6 h-4" /> },
  { code: "RU", name: "Russia", flag: <RU title="Russia" className="w-6 h-4" /> },
  { code: "UA", name: "Ukraine", flag: <UA title="Ukraine" className="w-6 h-4" /> },
  { code: "RO", name: "Romania", flag: <RO title="Romania" className="w-6 h-4" /> },
  { code: "BG", name: "Bulgaria", flag: <BG title="Bulgaria" className="w-6 h-4" /> },
  { code: "HR", name: "Croatia", flag: <HR title="Croatia" className="w-6 h-4" /> },
  { code: "SI", name: "Slovenia", flag: <SI title="Slovenia" className="w-6 h-4" /> },
  { code: "SK", name: "Slovakia", flag: <SK title="Slovakia" className="w-6 h-4" /> },
  { code: "LT", name: "Lithuania", flag: <LT title="Lithuania" className="w-6 h-4" /> },
  { code: "LV", name: "Latvia", flag: <LV title="Latvia" className="w-6 h-4" /> },
  { code: "EE", name: "Estonia", flag: <EE title="Estonia" className="w-6 h-4" /> },
  { code: "IS", name: "Iceland", flag: <IS title="Iceland" className="w-6 h-4" /> },
  { code: "LU", name: "Luxembourg", flag: <LU title="Luxembourg" className="w-6 h-4" /> },
  { code: "MT", name: "Malta", flag: <MT title="Malta" className="w-6 h-4" /> },
  { code: "CY", name: "Cyprus", flag: <CY title="Cyprus" className="w-6 h-4" /> },
  { code: "NZ", name: "New Zealand", flag: <NZ title="New Zealand" className="w-6 h-4" /> },
];
